# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d803544e65c5e9e94de1cbea12f2ca93ed11675bb76f869de2bc46619ef5cd3f394f0f59ca6523510184508efc5114c3819742d3853a18f07bc75a4b7cce81

test:
  secret_key_base: 38b55327734a26c886fb1123cffaf6b3450c8d473e38fe2ca2d78e4ea9eaf8b77d45496616b7d21f94f3c0b98409065e3a880b08a8b28dc375fb5536d40a360f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
